### PR TITLE
Feat: share buttons

### LINKED ISSUE #25: feature: share buttons

### PR DESCRIPTION
**Pull request by squigglybob**
resolves #25 

Add a share button in the app so that all users have an easy way to share the app with people.

In the GoNative app this will use the GoNative share functionality
Falling back to the web API share,
falling back to a modal with some specific share buttons, like copy url, facebook, twitter etc.

image

### CODE REVIEW

**Comment by squigglybob** [comment]
on desktop or browser/devices without a native share option, a modal will show up
image

**Comment by squigglybob** [comment]
twitter isn't pulling in the image for some reason, but could be a simple thing e.g. https://stackoverflow.com/questions/66810391/twitter-open-graph-image-not-showing

image

facebook is fine
image

**Comment by squigglybob** [comment]
@ChrisChasm The share modal seems to be working well except for that one thing with the twitter share not picking up the image for somereason.

I haven't been able to test the native share on mobile browser, or gonative app. hopefully we can test flight it? although doesn't changing the live site, automatically change the content of the app? as it's just a webview of the site?

I'm still wondering wether it's worth having a staging site for live testing purposes?

**Comment by ChrisChasm** [comment]
> @ChrisChasm The share modal seems to be working well except for that one thing with the twitter share not picking up the image for somereason.


This might be a missing meta tag in the header. Did you confirm that we have the twitter meta tag for images?

**Comment by ChrisChasm** [comment]
So I like how the modal is working a lot. But in this version, you have the Start Praying button to the left. I would like to keep it in the same location for the full site. Ideally to the right. 

Is this PR compatible with the new navigation PR?

**Comment by ChrisChasm** [comment]
I think the share button could be added:
1. at the bottom of the off canvas navigation menu
https://www.loom.com/share/7be7989de96745bfac37529e3ae67a53

2. at the right side of the map
https://www.loom.com/share/57d25256b2df4fa8b99a9fd58eaec836

**Comment by squigglybob** [comment]
@ChrisChasm 
Full screen
image

Just above breakpoint
image

Small screen
image

**Comment by ChrisChasm** [comment]
Tweak, share button on map footer: 
I think because the share button is available in the flyout menu, and it is wonky for the mobile screen footer, can we hide it on mobile for the map?

Screenshot 2022-11-16 at 6 55 38 AM

**Pull request merged**
