### PR TITLE
feat: change prayer warrior image to praying hands

### PR DESCRIPTION
**Pull request by squigglybob**
Here is an example of how that could work...

image
and the icons getting twice as big as this as you zoom in
image

I'm not sure I 100% like this, and was wondering about siluetting the praying hands to see what that would look like.

(edit, the silouetted hands look like an eiffel tower or something, not great)

One thing I noticed when trying transparency on the icons, was that some icons were more transparent than others...
I imagine that this is from multiple rows in the reports table from the same person praying for multiple places in one go, and each of those records counting towards a participant in the list of participants? Just a guess, but that would make sense of some hands being less transparent than others...

What do you think @ChrisChasm ?

### CODE REVIEW

**Comment by squigglybob** [comment]
outline praying hands?
image

**Comment by squigglybob** [comment]
or someone at the summit suggested fire?
image
looks pretty cool I think

**Comment by himayrunner** [comment]
@squigglybob could we see the flames and praying hands far smaller, just to see what that would look like? 
also, is there a different place where you are tracking the idea about the different color outlines?

**Comment by squigglybob** [comment]
Before was at 25% size
This is at 15% size
image
This is at 5% size
image

15%
image
5%
image

**Comment by squigglybob** [comment]
@himayrunner at the moment no, we haven't yet tackled colour changes of the map (is that what you're referring to?)

**Comment by ChrisChasm** [comment]
I think we need to hold on this modification. I'm not sure either the fire or the hands is getting to what we want visually. I think we need to work out the idea in Photoshop, and get to a final visual.

**Pull request closed without merging**
