### PR TITLE
refactor: foundation classes to bootstrap in global map

### LINKED ISSUE #24: upgrade stylesheets and navs

### PR DESCRIPTION
**Pull request by squigglybob**
This refactor will need Bootstrap to be upgraded from 4.0.0-beta where it is now, to version 5 in order to replace the foundation off-canvas panels with Bootstrap.

resolves #24

### CODE REVIEW

**Comment by squigglybob** [comment]
@ChrisChasm 
nav-links

hover and clicked modes for the more button like nav items

**Comment by squigglybob** [comment]
@ChrisChasm This one should be good to review now

**Comment by ChrisChasm** [comment]
I sent you a loom, but I'm not getting something to load or a dependency, or something. https://www.loom.com/share/e68ed1374e044be9be7a22e58479a17b

**Comment by squigglybob** [comment]
@ChrisChasm I've added the js map file, and even though my screen registered it looking like yours, it flicked back to normal pretty quickly after I navigated to the map screen. Not sure what's going on there 😬

**Pull request merged**
